### ISSUE TITLE
Question: onFlush vs preFlush

### ISSUE THREAD

**Issue by martinssipenko** [headsnet/domain-events-bundle#24]
Hi, 

I've been reading through your code and have noticed that you subscribe your [`PersistDomainEventSubscriber` to Doctrines `onFlush` event](https://github.com/headsnet/domain-events-bundle/blob/b789824b5dacd77c485b413eae10a9e469555087/src/Doctrine/EventSubscriber/PersistDomainEventSubscriber.php#L39). I'm not saying there is anything wrong with it just trying to understand why exactly `onFlush` event is used instead of `preFlush`? When running code locally I discovered that using `preFlush` removed the need to `computeChangeSet()` in [`DoctrineEventStore` line 86](https://github.com/headsnet/domain-events-bundle/blob/b789824b5dacd77c485b413eae10a9e469555087/src/Doctrine/DoctrineEventStore.php#L85-L86). Perhaps you could point out to me why is it like this?

**Comment by benr77** [comment]
`computeChangeSet()` is required when you persist new entities in the `onFlush` event. This is needed because we are persisting the event entity to the event store during the `onFlush` event.

The `onFlush` event itself is listened to, because we need access to the Unit Of Work, provided by this event, in order to extract all the recorded events - see `Headsnet\DomainEventsBundle\Doctrine\EventSubscriber\PersistDomainEventSubscriber` for how this extracts the events for entities and collections of entities from the UOW.

**Comment by martinssipenko** [comment]
Thanks for the prompt answer! A few follow up questions:
- Is there a reason why `preFlush` event can't be used? It too has `EntityManager` available through which UOW can be accessed?
- At which point does the table for storing domain events gets created?

**Comment by benr77** [comment]
The computed changeset isn't available during `preFlush` - it's only ready in `onFlush`.

The database table is created via a Doctrine migration - as long as the bundle is installed, your next migration will contain the relevant SQL.

**Comment by martinssipenko** [comment]
Thank you! I'm closing this, I hope you don't mind me posting some more questions here if I have them further down the line. Right now I'm looking at how would the code behave in a multi-instance setup and cases where dispatching to event bus fails for some reason. I guess I'll just need to run the code to see how it behaves.
